services:
  bot:
    build:
      context: .
    container_name: discord_bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "node", "dist/main.js" ]
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment: POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres POSTGRES_DB=botdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
